# Generated by Django 4.0.2 on 2022-06-01 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('slug', models.SlugField(default=None, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField()),
                ('post_Main_Img', models.ImageField(blank=True, upload_to='C:\\Users\\pheng\\OneDrive\\Documents\\GitHub\\smallwebsite\\phengkhai\\images')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_posts', to=settings.AUTH_USER_MODEL)),
                ('general_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioPage.category')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
