# Generated by Django 4.0.2 on 2022-06-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='general_category',
            field=models.IntegerField(choices=[(0, 'Undecided'), (1, 'Webapp'), (2, 'Game')], default=0),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
