# Generated by Django 4.0.2 on 2022-06-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioPage', '0002_alter_projects_general_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='general_category',
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.IntegerField(choices=[(0, 'Undecided'), (1, 'Webapp'), (2, 'Game')], default=0),
        ),
    ]
