# Generated by Django 4.0.2 on 2022-06-03 17:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioPage', '0006_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
