# Generated by Django 4.0.2 on 2022-07-22 23:56

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioPage', '0008_alter_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.CharField(default=builtins.print, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
