# Generated by Django 4.0.2 on 2022-07-22 23:59

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioPage', '0009_projects_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=200, null=sqlalchemy.sql.expression.true, unique=True),
        ),
    ]
