# Generated by Django 4.0.2 on 2022-07-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioPage', '0010_alter_projects_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
