# Generated by Django 4.0.2 on 2022-07-23 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioPage', '0011_alter_projects_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='link',
        ),
    ]
