# Generated by Django 4.0.2 on 2022-05-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0002_post_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hotel_Main_Img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
