# Generated by Django 4.0.2 on 2022-05-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0003_post_hotel_main_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hotel_Main_Img',
        ),
    ]
