# Generated by Django 4.0.2 on 2022-05-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0005_post_post_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_Main_Img',
            field=models.ImageField(blank=True, upload_to='C:\\Users\\pheng\\OneDrive\\Documents\\GitHub\\smallwebsite\\phengkhai\\images'),
        ),
    ]
