# Generated by Django 4.0.2 on 2022-07-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_Main_Img',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
